spring:
  kafka:
    bootstrap-servers: ""
    producer:
      acks: 0
      properties:
        max.block.ms: 100
        retries: 0
        metadata.max.age.ms: 100
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

management:
  endpoint:
    health:
      group:
        readiness:
          include: livenessState

logging:
  level:
    com.odevpedro.yugiohcollections.duel: DEBUG

duel:
  auth:
    enabled: false
